"""empty message

Revision ID: 00621eac61be
Revises: 082dc323aa85
Create Date: 2016-11-14 06:01:21.842525

"""

# revision identifiers, used by Alembic.
revision = '00621eac61be'
down_revision = '082dc323aa85'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wireless_sim_order', sa.Column('phone_type', sa.String(length=30), nullable=True))
    op.drop_index('ix_wireless_sim_order_sim_number', table_name='wireless_sim_order')
    op.drop_column('wireless_sim_order', 'user_name')
    op.drop_column('wireless_sim_order', 'sim_number')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wireless_sim_order', sa.Column('sim_number', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('wireless_sim_order', sa.Column('user_name', mysql.VARCHAR(length=100), nullable=True))
    op.create_index('ix_wireless_sim_order_sim_number', 'wireless_sim_order', ['sim_number'], unique=False)
    op.drop_column('wireless_sim_order', 'phone_type')
    ### end Alembic commands ###
