"""empty message

Revision ID: 082dc323aa85
Revises: ed2f2476d6f4
Create Date: 2016-11-14 02:44:04.722758

"""

# revision identifiers, used by Alembic.
revision = '082dc323aa85'
down_revision = 'ed2f2476d6f4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wireless_sim_order', 'registered_date')
    op.drop_column('wireless_sim_order', 'passport_img')
    op.drop_column('wireless_sim_order', 'registered_phone')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wireless_sim_order', sa.Column('registered_phone', mysql.VARCHAR(length=12), nullable=True))
    op.add_column('wireless_sim_order', sa.Column('passport_img', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('wireless_sim_order', sa.Column('registered_date', mysql.DATETIME(), nullable=True))
    ### end Alembic commands ###
