"""empty message

Revision ID: 198b53f07174
Revises: aadd4febd560
Create Date: 2017-02-06 06:23:20.868980

"""

# revision identifiers, used by Alembic.
revision = '198b53f07174'
down_revision = 'aadd4febd560'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wireless_recharge', sa.Column('activated_wireless_id', sa.Integer(), nullable=True))
    op.add_column('wireless_recharge', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.add_column('wireless_recharge', sa.Column('payment_method', sa.String(length=20), nullable=True))
    op.add_column('wireless_recharge', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_wireless_recharge_user_id'), 'wireless_recharge', ['user_id'], unique=False)
    op.drop_constraint('wireless_recharge_ibfk_1', 'wireless_recharge', type_='foreignkey')
    op.create_foreign_key(None, 'wireless_recharge', 'payment', ['payment_id'], ['id'])
    op.create_foreign_key(None, 'wireless_recharge', 'auth_users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'wireless_recharge', 'wireless_sim_activate', ['activated_wireless_id'], ['id'])
    op.drop_column('wireless_recharge', 'activated_wireless')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wireless_recharge', sa.Column('activated_wireless', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'wireless_recharge', type_='foreignkey')
    op.drop_constraint(None, 'wireless_recharge', type_='foreignkey')
    op.drop_constraint(None, 'wireless_recharge', type_='foreignkey')
    op.create_foreign_key('wireless_recharge_ibfk_1', 'wireless_recharge', 'wireless_sim_activate', ['activated_wireless'], ['id'])
    op.drop_index(op.f('ix_wireless_recharge_user_id'), table_name='wireless_recharge')
    op.drop_column('wireless_recharge', 'user_id')
    op.drop_column('wireless_recharge', 'payment_method')
    op.drop_column('wireless_recharge', 'payment_id')
    op.drop_column('wireless_recharge', 'activated_wireless_id')
    ### end Alembic commands ###
