"""empty message

Revision ID: 1ace91739e83
Revises: f06018ed0da9
Create Date: 2017-01-02 14:34:18.723613

"""

# revision identifiers, used by Alembic.
revision = '1ace91739e83'
down_revision = 'f06018ed0da9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('order', sa.Column('total', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.drop_column('order', 'total_amount')
    op.drop_column('order', 'amount')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('amount', mysql.DECIMAL(precision=10, scale=0), nullable=True))
    op.add_column('order', sa.Column('total_amount', mysql.DECIMAL(precision=10, scale=0), nullable=True))
    op.drop_column('order', 'total')
    op.drop_column('order', 'subtotal')
    ### end Alembic commands ###
