"""empty message

Revision ID: 1bad5c16033e
Revises: ab5b28a7843e
Create Date: 2016-11-17 12:55:06.589369

"""

# revision identifiers, used by Alembic.
revision = '1bad5c16033e'
down_revision = 'ab5b28a7843e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'catalogue_product_image', 'catalogue_product', ['product_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catalogue_product_image', type_='foreignkey')
    ### end Alembic commands ###
