"""empty message

Revision ID: 24e7fd93ed58
Revises: a6bb7abb1d4d
Create Date: 2016-11-11 16:10:43.040272

"""

# revision identifiers, used by Alembic.
revision = '24e7fd93ed58'
down_revision = 'a6bb7abb1d4d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogue_product_cart', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('catalogue_product_cart', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index('ix_catalogue_product_cart_name', table_name='catalogue_product_cart')
    op.create_foreign_key(None, 'catalogue_product_cart', 'auth_users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'catalogue_product_cart', 'catalogue_product', ['product_id'], ['id'])
    op.drop_column('catalogue_product_cart', 'description')
    op.drop_column('catalogue_product_cart', 'currency')
    op.drop_column('catalogue_product_cart', 'name')
    op.drop_column('catalogue_product_cart', 'price')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogue_product_cart', sa.Column('price', mysql.DECIMAL(precision=10, scale=0), nullable=True))
    op.add_column('catalogue_product_cart', sa.Column('name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('catalogue_product_cart', sa.Column('currency', mysql.CHAR(length=3), nullable=True))
    op.add_column('catalogue_product_cart', sa.Column('description', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'catalogue_product_cart', type_='foreignkey')
    op.drop_constraint(None, 'catalogue_product_cart', type_='foreignkey')
    op.create_index('ix_catalogue_product_cart_name', 'catalogue_product_cart', ['name'], unique=False)
    op.drop_column('catalogue_product_cart', 'user_id')
    op.drop_column('catalogue_product_cart', 'product_id')
    ### end Alembic commands ###
