"""empty message

Revision ID: 28cb26638a73
Revises: 654a86a89631
Create Date: 2017-01-20 13:38:01.896648

"""

# revision identifiers, used by Alembic.
revision = '28cb26638a73'
down_revision = '654a86a89631'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'wireless_sim_order', 'address_country', ['shipping_iso_3166_country'], ['iso_3166_1_a2'])
    op.drop_column('wireless_sim_order', 'rcv_address3')
    op.drop_column('wireless_sim_order', 'rcv_address2')
    op.drop_column('wireless_sim_order', 'rcv_date')
    op.drop_column('wireless_sim_order', 'rcv_extra_address')
    op.drop_column('wireless_sim_order', 'user_email')
    op.drop_column('wireless_sim_order', 'rcv_address1')
    op.drop_column('wireless_sim_order', 'shipping_method')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wireless_sim_order', sa.Column('shipping_method', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('wireless_sim_order', sa.Column('rcv_address1', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('wireless_sim_order', sa.Column('user_email', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('wireless_sim_order', sa.Column('rcv_extra_address', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('wireless_sim_order', sa.Column('rcv_date', sa.DATE(), nullable=True))
    op.add_column('wireless_sim_order', sa.Column('rcv_address2', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('wireless_sim_order', sa.Column('rcv_address3', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'wireless_sim_order', type_='foreignkey')
    ### end Alembic commands ###
