"""empty message

Revision ID: 2c8f3286f425
Revises: bc5cb4310d10
Create Date: 2017-01-24 17:34:45.826716

"""

# revision identifiers, used by Alembic.
revision = '2c8f3286f425'
down_revision = 'bc5cb4310d10'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_return', sa.Column('status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_return', 'status')
    ### end Alembic commands ###
