"""empty message

Revision ID: 2e813883cc88
Revises: 24cf0dad97a2
Create Date: 2016-11-15 15:40:46.223725

"""

# revision identifiers, used by Alembic.
revision = '2e813883cc88'
down_revision = '24cf0dad97a2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogue_product_cart', sa.Column('status', sa.Enum('Open', 'Merged', 'Saved', 'Frozen', 'Submitted', name='status_choices'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalogue_product_cart', 'status')
    ### end Alembic commands ###
