"""empty message

Revision ID: 320c8bf5163b
Revises: f539fed3e8c1
Create Date: 2016-12-27 14:47:02.945912

"""

# revision identifiers, used by Alembic.
revision = '320c8bf5163b'
down_revision = 'f539fed3e8c1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address_user_address', sa.Column('city', sa.String(length=80), nullable=True))
    op.add_column('address_user_address', sa.Column('line1', sa.String(length=80), nullable=True))
    op.add_column('address_user_address', sa.Column('line2', sa.String(length=80), nullable=True))
    op.add_column('address_user_address', sa.Column('state', sa.String(length=80), nullable=True))
    op.drop_column('address_user_address', 'address2')
    op.drop_column('address_user_address', 'address3')
    op.drop_column('address_user_address', 'province')
    op.drop_column('address_user_address', 'address1')
    op.add_column('order', sa.Column('billing_city', sa.String(length=80), nullable=True))
    op.add_column('order', sa.Column('billing_line1', sa.String(length=80), nullable=True))
    op.add_column('order', sa.Column('billing_line2', sa.String(length=80), nullable=True))
    op.add_column('order', sa.Column('billing_state', sa.String(length=80), nullable=True))
    op.add_column('order', sa.Column('shipping_city', sa.String(length=80), nullable=True))
    op.add_column('order', sa.Column('shipping_line1', sa.String(length=80), nullable=True))
    op.add_column('order', sa.Column('shipping_line2', sa.String(length=80), nullable=True))
    op.add_column('order', sa.Column('shipping_state', sa.String(length=80), nullable=True))
    op.drop_column('order', 'billing_addr2')
    op.drop_column('order', 'shipping_addr1')
    op.drop_column('order', 'shipping_addr2')
    op.drop_column('order', 'billing_addr3')
    op.drop_column('order', 'shipping_province')
    op.drop_column('order', 'shipping_addr3')
    op.drop_column('order', 'billing_addr1')
    op.drop_column('order', 'billing_province')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('billing_province', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('order', sa.Column('billing_addr1', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('order', sa.Column('shipping_addr3', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('order', sa.Column('shipping_province', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('order', sa.Column('billing_addr3', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('order', sa.Column('shipping_addr2', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('order', sa.Column('shipping_addr1', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('order', sa.Column('billing_addr2', mysql.VARCHAR(length=80), nullable=True))
    op.drop_column('order', 'shipping_state')
    op.drop_column('order', 'shipping_line2')
    op.drop_column('order', 'shipping_line1')
    op.drop_column('order', 'shipping_city')
    op.drop_column('order', 'billing_state')
    op.drop_column('order', 'billing_line2')
    op.drop_column('order', 'billing_line1')
    op.drop_column('order', 'billing_city')
    op.add_column('address_user_address', sa.Column('address1', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('address_user_address', sa.Column('province', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('address_user_address', sa.Column('address3', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('address_user_address', sa.Column('address2', mysql.VARCHAR(length=80), nullable=True))
    op.drop_column('address_user_address', 'state')
    op.drop_column('address_user_address', 'line2')
    op.drop_column('address_user_address', 'line1')
    op.drop_column('address_user_address', 'city')
    ### end Alembic commands ###
