"""empty message

Revision ID: 36739f9d8074
Revises: 407dd795a114
Create Date: 2016-11-07 16:30:14.647528

"""

# revision identifiers, used by Alembic.
revision = '36739f9d8074'
down_revision = '407dd795a114'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wireless_sim_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.CHAR(length=6), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wireless_sim_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('rcv_country', sa.String(length=2), nullable=True),
    sa.Column('rcv_address1', sa.String(length=255), nullable=True),
    sa.Column('rcv_address2', sa.String(length=255), nullable=True),
    sa.Column('rcv_address3', sa.String(length=255), nullable=True),
    sa.Column('sim_number', sa.String(length=20), nullable=True),
    sa.Column('order_state', sa.Integer(), nullable=True),
    sa.Column('registered_phone', sa.String(length=12), nullable=True),
    sa.Column('registered_date', sa.DateTime(), nullable=True),
    sa.Column('passport_img', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['wireless_sim_payment.id'], ),
    sa.ForeignKeyConstraint(['rcv_country'], ['address_country.iso_3166_1_a2'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wireless_sim_order_user_id'), 'wireless_sim_order', ['user_id'], unique=False)
    op.create_table('wireless_sim_topup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('topup_phone', sa.String(length=12), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=2), nullable=True),
    sa.Column('topup_state', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['wireless_sim_payment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wireless_sim_topup_payment_id'), 'wireless_sim_topup', ['payment_id'], unique=False)
    op.create_index(op.f('ix_wireless_sim_topup_user_id'), 'wireless_sim_topup', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wireless_sim_topup_user_id'), table_name='wireless_sim_topup')
    op.drop_index(op.f('ix_wireless_sim_topup_payment_id'), table_name='wireless_sim_topup')
    op.drop_table('wireless_sim_topup')
    op.drop_index(op.f('ix_wireless_sim_order_user_id'), table_name='wireless_sim_order')
    op.drop_table('wireless_sim_order')
    op.drop_table('wireless_sim_payment')
    ### end Alembic commands ###
