"""empty message

Revision ID: 37bea7a71701
Revises: b1701e405f74
Create Date: 2016-11-09 18:18:04.162172

"""

# revision identifiers, used by Alembic.
revision = '37bea7a71701'
down_revision = 'b1701e405f74'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('housing_enquiry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=55), nullable=True),
    sa.Column('email', sa.String(length=55), nullable=True),
    sa.Column('kakao_id', sa.String(length=55), nullable=True),
    sa.Column('mobile_no', sa.String(length=55), nullable=True),
    sa.Column('enquiry', sa.Text(), nullable=True),
    sa.Column('nationality', sa.String(length=55), nullable=True),
    sa.Column('enquiry_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_housing_enquiry_user_id'), 'housing_enquiry', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_housing_enquiry_user_id'), table_name='housing_enquiry')
    op.drop_table('housing_enquiry')
    ### end Alembic commands ###
