"""empty message

Revision ID: 3ccf989232b8
Revises: 320c8bf5163b
Create Date: 2016-12-29 17:04:53.630742

"""

# revision identifiers, used by Alembic.
revision = '3ccf989232b8'
down_revision = '320c8bf5163b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_category',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('is_display', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['crawl_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table(' crawl_category_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('crawl_category_id', sa.Integer(), nullable=True),
    sa.Column('lang_code', sa.CHAR(length=4), nullable=True),
    sa.ForeignKeyConstraint(['crawl_category_id'], ['crawl_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ crawl_category_detail_lang_code'), ' crawl_category_detail', ['lang_code'], unique=False)
    op.create_index(op.f('ix_ crawl_category_detail_name'), ' crawl_category_detail', ['name'], unique=True)
    op.create_table('crawl_product',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('structure', sa.CHAR(length=10), nullable=True),
    sa.Column('upc', sa.String(length=64), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['crawl_category.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['crawl_product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upc')
    )
    op.create_table('crawl_product_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lang_code', sa.CHAR(length=4), nullable=True),
    sa.Column('crawl_product_id', sa.Integer(), nullable=True),
    sa.Column('is_display', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['crawl_product_id'], ['crawl_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_product_detail_lang_code'), 'crawl_product_detail', ['lang_code'], unique=False)
    op.create_index(op.f('ix_crawl_product_detail_name'), 'crawl_product_detail', ['name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crawl_product_detail_name'), table_name='crawl_product_detail')
    op.drop_index(op.f('ix_crawl_product_detail_lang_code'), table_name='crawl_product_detail')
    op.drop_table('crawl_product_detail')
    op.drop_table('crawl_product')
    op.drop_index(op.f('ix_ crawl_category_detail_name'), table_name=' crawl_category_detail')
    op.drop_index(op.f('ix_ crawl_category_detail_lang_code'), table_name=' crawl_category_detail')
    op.drop_table(' crawl_category_detail')
    op.drop_table('crawl_category')
    ### end Alembic commands ###
