"""empty message

Revision ID: 3e99f83094d6
Revises: 2e813883cc88
Create Date: 2016-11-15 15:56:59.999453

"""

# revision identifiers, used by Alembic.
revision = '3e99f83094d6'
down_revision = '2e813883cc88'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogue_product_cart', sa.Column('date_merged', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalogue_product_cart', 'date_merged')
    ### end Alembic commands ###
