"""empty message

Revision ID: 407dd795a114
Revises: f97dd75954b0
Create Date: 2016-11-04 16:11:39.446877

"""

# revision identifiers, used by Alembic.
revision = '407dd795a114'
down_revision = 'f97dd75954b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogue_category', sa.Column('slug', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalogue_category', 'slug')
    ### end Alembic commands ###
