"""empty message

Revision ID: 44fa9f409410
Revises: a17618c44c77
Create Date: 2016-11-15 22:09:06.579546

"""

# revision identifiers, used by Alembic.
revision = '44fa9f409410'
down_revision = 'a17618c44c77'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogue_product', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.alter_column('catalogue_product', 'upc',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.create_foreign_key(None, 'catalogue_product', 'catalogue_product', ['parent_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catalogue_product', type_='foreignkey')
    op.alter_column('catalogue_product', 'upc',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.drop_column('catalogue_product', 'parent_id')
    ### end Alembic commands ###
