"""empty message

Revision ID: 4863ef754c76
Revises: 9df673ad1b52
Create Date: 2017-01-04 12:40:58.366197

"""

# revision identifiers, used by Alembic.
revision = '4863ef754c76'
down_revision = '9df673ad1b52'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order_association', 'catalogue_product', ['product_id'], ['id'])
    op.drop_column('order_association', 'upc')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_association', sa.Column('upc', mysql.VARCHAR(length=64), nullable=False))
    op.drop_constraint(None, 'order_association', type_='foreignkey')
    ### end Alembic commands ###
