"""empty message

Revision ID: 4a9b46047698
Revises: da5963e0304d
Create Date: 2017-01-11 13:13:14.541833

"""

# revision identifiers, used by Alembic.
revision = '4a9b46047698'
down_revision = 'da5963e0304d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('name', sa.String(length=65), nullable=True))
    op.drop_column('order', 'recipient_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('recipient_name', mysql.VARCHAR(length=65), nullable=True))
    op.drop_column('order', 'name')
    ### end Alembic commands ###
