"""empty message

Revision ID: 5445fdb31bfd
Revises: 5be19a3b9653
Create Date: 2016-11-28 10:28:54.273010

"""

# revision identifiers, used by Alembic.
revision = '5445fdb31bfd'
down_revision = '5be19a3b9653'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogue_product_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('additional_price', sa.DECIMAL(precision=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalogue_product_option')
    ### end Alembic commands ###
