"""empty message

Revision ID: 575c0f133a28
Revises: 28cb26638a73
Create Date: 2017-01-22 21:10:29.082989

"""

# revision identifiers, used by Alembic.
revision = '575c0f133a28'
down_revision = '28cb26638a73'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogue_product_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('category_code_id', sa.Integer(), nullable=True),
    sa.Column('product_attribute', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['category_code_id'], ['catalogue_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribute_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('catalogue_product_attribute_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['catalogue_product_attribute_id'], ['catalogue_product_attribute.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalogue_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_return',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('exchange_refund', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order_association.product_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['order_association.order_id'], ),
    sa.PrimaryKeyConstraint('id', 'order_id', 'product_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_return')
    op.drop_table('attribute_association')
    op.drop_table('catalogue_product_attribute')
    ### end Alembic commands ###
