"""empty message

Revision ID: 5acd337a4e42
Revises: 37bea7a71701
Create Date: 2016-11-11 13:59:38.573876

"""

# revision identifiers, used by Alembic.
revision = '5acd337a4e42'
down_revision = '37bea7a71701'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wireless_sim_order', sa.Column('user_country', sa.CHAR(length=2), nullable=True))
    op.drop_constraint('wireless_sim_order_ibfk_2', 'wireless_sim_order', type_='foreignkey')
    op.create_foreign_key(None, 'wireless_sim_order', 'address_country', ['user_country'], ['iso_3166_1_a2'])
    op.drop_column('wireless_sim_order', 'rcv_country')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wireless_sim_order', sa.Column('rcv_country', mysql.VARCHAR(length=2), nullable=True))
    op.drop_constraint(None, 'wireless_sim_order', type_='foreignkey')
    op.create_foreign_key('wireless_sim_order_ibfk_2', 'wireless_sim_order', 'address_country', ['rcv_country'], ['iso_3166_1_a2'])
    op.drop_column('wireless_sim_order', 'user_country')
    ### end Alembic commands ###
