"""empty message

Revision ID: 5be19a3b9653
Revises: 691f5d32f572
Create Date: 2016-11-21 11:37:15.541605

"""

# revision identifiers, used by Alembic.
revision = '5be19a3b9653'
down_revision = '691f5d32f572'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogue_category', sa.Column('is_display', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalogue_category', 'is_display')
    ### end Alembic commands ###
