"""empty message

Revision ID: 654a86a89631
Revises: 724568b3fdec
Create Date: 2017-01-20 13:24:12.958128

"""

# revision identifiers, used by Alembic.
revision = '654a86a89631'
down_revision = '724568b3fdec'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint('wireless_sim_order_ibfk_1', 'wireless_sim_order', type_='foreignkey')
    op.create_foreign_key(None, 'wireless_sim_order', 'address_country', ['shipping_iso_3166_country'], ['iso_3166_1_a2'])
    op.drop_column('wireless_sim_order', 'rcv_date')
    op.drop_column('wireless_sim_order', 'shipping_method')
    op.drop_column('wireless_sim_order', 'rcv_address1')
    op.drop_column('wireless_sim_order', 'rcv_address3')
    op.drop_column('wireless_sim_order', 'user_email')
    op.drop_column('wireless_sim_order', 'rcv_address2')
    op.drop_column('wireless_sim_order', 'rcv_extra_address')
    op.drop_column('wireless_sim_order', 'payment_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wireless_sim_order', sa.Column('payment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('wireless_sim_order', sa.Column('rcv_extra_address', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('wireless_sim_order', sa.Column('rcv_address2', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('wireless_sim_order', sa.Column('user_email', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('wireless_sim_order', sa.Column('rcv_address3', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('wireless_sim_order', sa.Column('rcv_address1', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('wireless_sim_order', sa.Column('shipping_method', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('wireless_sim_order', sa.Column('rcv_date', sa.DATE(), nullable=True))
    op.drop_constraint(None, 'wireless_sim_order', type_='foreignkey')
    op.create_foreign_key('wireless_sim_order_ibfk_1', 'wireless_sim_order', 'wireless_sim_payment', ['payment_id'], ['id'])
    op.drop_column('wireless_sim_order', 'sim_type')
    op.drop_column('wireless_sim_order', 'sim_number')
    op.drop_column('wireless_sim_order', 'shipping_state')
    op.drop_column('wireless_sim_order', 'shipping_line2')
    op.drop_column('wireless_sim_order', 'shipping_line1')
    op.drop_column('wireless_sim_order', 'shipping_iso_3166_country')
    op.drop_column('wireless_sim_order', 'shipping_city')
    op.drop_column('wireless_sim_order', 'price')
    op.drop_column('wireless_sim_order', 'payment_method')
    op.drop_column('wireless_sim_order', 'message')
    op.drop_column('wireless_sim_order', 'last_name')
    op.drop_column('wireless_sim_order', 'first_name')
    op.drop_column('wireless_sim_order', 'email')
    op.drop_column('wireless_sim_order', 'currency')
    op.drop_column('wireless_sim_order', 'contact_no')
    op.create_table('wireless_sim_order_product',
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['wireless_sim_order.id'], name='wireless_sim_order_product_ibfk_1'),
    sa.ForeignKeyConstraint(['product_id'], ['wireless_sim_product.id'], name='wireless_sim_order_product_ibfk_2'),
    sa.PrimaryKeyConstraint('product_id', 'order_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('wireless_sim_payment',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('modified_at', mysql.DATETIME(), nullable=True),
    sa.Column('payment_method', mysql.CHAR(length=6), nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=2, scale=0), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('wireless_sim_topup',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('modified_at', mysql.DATETIME(), nullable=True),
    sa.Column('topup_phone', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=2, scale=0), nullable=True),
    sa.Column('topup_state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('payment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('activate_sim', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_initial', mysql.VARCHAR(length=12), nullable=True),
    sa.ForeignKeyConstraint(['activate_sim'], ['wireless_sim_activate.id'], name='wireless_sim_topup_ibfk_3'),
    sa.ForeignKeyConstraint(['payment_id'], ['wireless_sim_payment.id'], name='wireless_sim_topup_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], name='wireless_sim_topup_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('wireless_sim_product',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('modified_at', mysql.DATETIME(), nullable=True),
    sa.Column('sim_number', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('sim_type', mysql.CHAR(length=2), nullable=True),
    sa.Column('is_sold', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_activated', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###
