"""empty message

Revision ID: 66c74195c217
Revises: d4a24cb59d9d
Create Date: 2016-11-02 17:26:12.285441

"""

# revision identifiers, used by Alembic.
revision = '66c74195c217'
down_revision = 'd4a24cb59d9d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogue_product_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['catalogue_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalogue_product_image')
    ### end Alembic commands ###
