"""empty message

Revision ID: 6f5fcc81eb07
Revises: fc21f4e4392c
Create Date: 2016-11-02 15:35:34.622053

"""

# revision identifiers, used by Alembic.
revision = '6f5fcc81eb07'
down_revision = 'fc21f4e4392c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogue_category', sa.Column('depth', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_catalogue_category_name'), 'catalogue_category', ['name'], unique=True)
    op.drop_index('name', table_name='catalogue_category')
    op.drop_constraint('catalogue_category_ibfk_1', 'catalogue_category', type_='foreignkey')
    op.create_foreign_key(None, 'catalogue_category', 'catalogue_category', ['parent_id'], ['id'])
    op.drop_column('catalogue_category', 'child_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogue_category', sa.Column('child_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'catalogue_category', type_='foreignkey')
    op.create_foreign_key('catalogue_category_ibfk_1', 'catalogue_category', 'catalogue_category', ['child_id'], ['id'])
    op.create_index('name', 'catalogue_category', ['name'], unique=True)
    op.drop_index(op.f('ix_catalogue_category_name'), table_name='catalogue_category')
    op.drop_column('catalogue_category', 'depth')
    ### end Alembic commands ###
