"""empty message

Revision ID: 70b530806c8e
Revises: 861d6b2e70d2
Create Date: 2016-11-16 15:34:25.451970

"""

# revision identifiers, used by Alembic.
revision = '70b530806c8e'
down_revision = '861d6b2e70d2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housing_image', sa.Column('housing_id', sa.Integer(), nullable=True))
    op.drop_constraint('housing_image_ibfk_1', 'housing_image', type_='foreignkey')
    op.create_foreign_key(None, 'housing_image', 'housing_services', ['housing_id'], ['id'])
    op.drop_column('housing_image', 'room_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housing_image', sa.Column('room_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'housing_image', type_='foreignkey')
    op.create_foreign_key('housing_image_ibfk_1', 'housing_image', 'housing_services', ['room_id'], ['id'])
    op.drop_column('housing_image', 'housing_id')
    ### end Alembic commands ###
