"""empty message

Revision ID: 724568b3fdec
Revises: 8b33d94501db
Create Date: 2017-01-16 20:35:01.127926

"""

# revision identifiers, used by Alembic.
revision = '724568b3fdec'
down_revision = '8b33d94501db'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_association', sa.Column('status', sa.Integer(), nullable=True))
    op.drop_column('order_association', 'test')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_association', sa.Column('test', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('order_association', 'status')
    ### end Alembic commands ###
