"""empty message

Revision ID: 7a8eb51d4613
Revises: 4863ef754c76
Create Date: 2017-01-04 14:26:22.240993

"""

# revision identifiers, used by Alembic.
revision = '7a8eb51d4613'
down_revision = '4863ef754c76'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_association', 'modified_at')
    op.drop_column('order_association', 'created_at')
    op.drop_column('order_association', 'id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_association', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('order_association', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('order_association', sa.Column('modified_at', mysql.DATETIME(), nullable=True))
    ### end Alembic commands ###
