"""empty message

Revision ID: 7acadbf11ce0
Revises: a0917f0cc187
Create Date: 2017-01-02 15:18:23.084781

"""

# revision identifiers, used by Alembic.
revision = '7acadbf11ce0'
down_revision = 'a0917f0cc187'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('shipping_fee', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.drop_column('order', 'shipping')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('shipping', mysql.DECIMAL(precision=10, scale=0), nullable=True))
    op.drop_column('order', 'shipping_fee')
    ### end Alembic commands ###
