"""empty message

Revision ID: 7c5e8e9dbab4
Revises: 94b030b84490
Create Date: 2017-02-01 10:58:39.353562

"""

# revision identifiers, used by Alembic.
revision = '7c5e8e9dbab4'
down_revision = '94b030b84490'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wireless_sim_activate', sa.Column('birthday', sa.CHAR(length=8), nullable=True))
    op.drop_column('wireless_sim_activate', 'birth_month')
    op.drop_column('wireless_sim_activate', 'birth_date')
    op.drop_column('wireless_sim_activate', 'birth_year')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wireless_sim_activate', sa.Column('birth_year', mysql.CHAR(length=4), nullable=True))
    op.add_column('wireless_sim_activate', sa.Column('birth_date', mysql.CHAR(length=2), nullable=True))
    op.add_column('wireless_sim_activate', sa.Column('birth_month', mysql.CHAR(length=2), nullable=True))
    op.drop_column('wireless_sim_activate', 'birthday')
    ### end Alembic commands ###
