"""empty message

Revision ID: 827e10a6f1c9
Revises: f193cd533d9a
Create Date: 2017-01-26 00:52:12.977428

"""

# revision identifiers, used by Alembic.
revision = '827e10a6f1c9'
down_revision = 'f193cd533d9a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('contact_number', sa.String(length=15), nullable=True))
    op.add_column('wireless_sim_activate', sa.Column('activate_date', sa.DateTime(), nullable=True))
    op.add_column('wireless_sim_activate', sa.Column('active_number', sa.String(length=16), nullable=True))
    op.add_column('wireless_sim_activate', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('wireless_sim_activate', sa.Column('birth_date', sa.CHAR(length=2), nullable=True))
    op.add_column('wireless_sim_activate', sa.Column('birth_month', sa.CHAR(length=2), nullable=True))
    op.add_column('wireless_sim_activate', sa.Column('birth_year', sa.CHAR(length=4), nullable=True))
    op.add_column('wireless_sim_activate', sa.Column('call_plan', sa.String(length=10), nullable=True))
    op.add_column('wireless_sim_activate', sa.Column('contact_no', sa.String(length=16), nullable=True))
    op.add_column('wireless_sim_activate', sa.Column('english_name', sa.String(length=50), nullable=True))
    op.add_column('wireless_sim_activate', sa.Column('id_number', sa.String(length=30), nullable=True))
    op.add_column('wireless_sim_activate', sa.Column('imei', sa.String(length=30), nullable=True))
    op.add_column('wireless_sim_activate', sa.Column('nationality', sa.CHAR(length=2), nullable=True))
    op.add_column('wireless_sim_activate', sa.Column('phone_model', sa.String(length=30), nullable=True))
    op.add_column('wireless_sim_activate', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('wireless_sim_activate', sa.Column('status_description', sa.String(length=255), nullable=True))
    op.drop_index('ix_wireless_sim_activate_phone_number', table_name='wireless_sim_activate')
    op.drop_column('wireless_sim_activate', 'active_date')
    op.drop_column('wireless_sim_activate', 'last_name')
    op.drop_column('wireless_sim_activate', 'is_active')
    op.drop_column('wireless_sim_activate', 'first_name')
    op.drop_column('wireless_sim_activate', 'is_activated')
    op.drop_column('wireless_sim_activate', 'phone_type')
    op.drop_column('wireless_sim_activate', 'phone_number')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wireless_sim_activate', sa.Column('phone_number', mysql.VARCHAR(length=12), nullable=True))
    op.add_column('wireless_sim_activate', sa.Column('phone_type', mysql.VARCHAR(length=40), nullable=True))
    op.add_column('wireless_sim_activate', sa.Column('is_activated', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('wireless_sim_activate', sa.Column('first_name', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('wireless_sim_activate', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('wireless_sim_activate', sa.Column('last_name', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('wireless_sim_activate', sa.Column('active_date', mysql.DATETIME(), nullable=True))
    op.create_index('ix_wireless_sim_activate_phone_number', 'wireless_sim_activate', ['phone_number'], unique=False)
    op.drop_column('wireless_sim_activate', 'status_description')
    op.drop_column('wireless_sim_activate', 'status')
    op.drop_column('wireless_sim_activate', 'phone_model')
    op.drop_column('wireless_sim_activate', 'nationality')
    op.drop_column('wireless_sim_activate', 'imei')
    op.drop_column('wireless_sim_activate', 'id_number')
    op.drop_column('wireless_sim_activate', 'english_name')
    op.drop_column('wireless_sim_activate', 'contact_no')
    op.drop_column('wireless_sim_activate', 'call_plan')
    op.drop_column('wireless_sim_activate', 'birth_year')
    op.drop_column('wireless_sim_activate', 'birth_month')
    op.drop_column('wireless_sim_activate', 'birth_date')
    op.drop_column('wireless_sim_activate', 'address')
    op.drop_column('wireless_sim_activate', 'active_number')
    op.drop_column('wireless_sim_activate', 'activate_date')
    op.drop_column('auth_users', 'contact_number')
    ### end Alembic commands ###
