"""empty message

Revision ID: 861d6b2e70d2
Revises: 9d4488074ba7
Create Date: 2016-11-16 14:13:47.444106

"""

# revision identifiers, used by Alembic.
revision = '861d6b2e70d2'
down_revision = '9d4488074ba7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_catalogue_category_category_code'), 'catalogue_category', ['category_code'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalogue_category_category_code'), table_name='catalogue_category')
    ### end Alembic commands ###
