"""empty message

Revision ID: 8a4d345fc213
Revises: 00621eac61be
Create Date: 2016-11-14 10:39:40.812442

"""

# revision identifiers, used by Alembic.
revision = '8a4d345fc213'
down_revision = '00621eac61be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wireless_sim_activate', sa.Column('is_activated', sa.Boolean(), nullable=True))
    op.add_column('wireless_sim_order', sa.Column('shipping_method', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wireless_sim_order', 'shipping_method')
    op.drop_column('wireless_sim_activate', 'is_activated')
    ### end Alembic commands ###
