"""empty message

Revision ID: 8b33d94501db
Revises: 4a9b46047698
Create Date: 2017-01-16 17:44:55.452504

"""

# revision identifiers, used by Alembic.
revision = '8b33d94501db'
down_revision = '4a9b46047698'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_association', sa.Column('test', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_association', 'test')
    ### end Alembic commands ###
