"""empty message

Revision ID: 92e81ee3adf1
Revises: da9e8912904a
Create Date: 2016-11-16 16:04:52.322840

"""

# revision identifiers, used by Alembic.
revision = '92e81ee3adf1'
down_revision = 'da9e8912904a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_catalogue_product_detail_lang_code'), 'catalogue_product_detail', ['lang_code'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalogue_product_detail_lang_code'), table_name='catalogue_product_detail')
    ### end Alembic commands ###
