"""empty message

Revision ID: 93b54650e9f7
Revises: c2583e59af10
Create Date: 2016-11-17 13:34:55.271100

"""

# revision identifiers, used by Alembic.
revision = '93b54650e9f7'
down_revision = 'c2583e59af10'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('catalogue_product_image_ibfk_1', 'catalogue_product_image', type_='foreignkey')
    op.create_foreign_key(None, 'catalogue_product_image', 'catalogue_product_detail', ['product_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catalogue_product_image', type_='foreignkey')
    op.create_foreign_key('catalogue_product_image_ibfk_1', 'catalogue_product_image', 'catalogue_product', ['product_id'], ['id'])
    ### end Alembic commands ###
