"""empty message

Revision ID: 940a0c14c357
Revises: 0cd96e32f88d
Create Date: 2017-01-24 16:28:01.034318

"""

# revision identifiers, used by Alembic.
revision = '940a0c14c357'
down_revision = '0cd96e32f88d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_return_ibfk_2', 'product_return', type_='foreignkey')
    op.drop_constraint('product_return_ibfk_1', 'product_return', type_='foreignkey')
    op.create_foreign_key(None, 'product_return', 'order_association', ['product_id'], ['product_id'])
    op.create_foreign_key(None, 'product_return', 'order_association', ['order_id'], ['order_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_return', type_='foreignkey')
    op.drop_constraint(None, 'product_return', type_='foreignkey')
    op.create_foreign_key('product_return_ibfk_1', 'product_return', 'catalogue_product', ['product_id'], ['id'])
    op.create_foreign_key('product_return_ibfk_2', 'product_return', 'order', ['order_id'], ['id'])
    ### end Alembic commands ###
