"""empty message

Revision ID: 9d4488074ba7
Revises: 44fa9f409410
Create Date: 2016-11-16 12:16:20.139495

"""

# revision identifiers, used by Alembic.
revision = '9d4488074ba7'
down_revision = '44fa9f409410'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogue_product_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('requires_shipping', sa.Boolean(), nullable=True),
    sa.Column('track_stock', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalogue_category_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('category_code_id', sa.Integer(), nullable=True),
    sa.Column('lang_code', sa.Enum('KR', 'CN', 'EN', name='lamg_choices'), nullable=True),
    sa.ForeignKeyConstraint(['category_code_id'], ['catalogue_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogue_category_detail_lang_code'), 'catalogue_category_detail', ['lang_code'], unique=False)
    op.create_index(op.f('ix_catalogue_category_detail_name'), 'catalogue_category_detail', ['name'], unique=True)
    op.create_table('catalogue_product_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lang_code', sa.Enum('KR', 'CN', 'EN', name='lamg_choices'), nullable=True),
    sa.Column('product_code_id', sa.Integer(), nullable=True),
    sa.Column('is_display', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_code_id'], ['catalogue_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogue_product_detail_name'), 'catalogue_product_detail', ['name'], unique=False)
    op.add_column('catalogue_category', sa.Column('category_code', sa.String(length=16), nullable=True))
    op.drop_index('ix_catalogue_category_name', table_name='catalogue_category')
    op.drop_column('catalogue_category', 'description')
    op.drop_column('catalogue_category', 'name')
    op.add_column('catalogue_product', sa.Column('type_id', sa.Integer(), nullable=True))
    op.alter_column('catalogue_product', 'price',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               nullable=False)
    op.drop_index('ix_catalogue_product_name', table_name='catalogue_product')
    op.create_foreign_key(None, 'catalogue_product', 'catalogue_product_type', ['type_id'], ['id'])
    op.drop_column('catalogue_product', 'description')
    op.drop_column('catalogue_product', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogue_product', sa.Column('name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('catalogue_product', sa.Column('description', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'catalogue_product', type_='foreignkey')
    op.create_index('ix_catalogue_product_name', 'catalogue_product', ['name'], unique=False)
    op.alter_column('catalogue_product', 'price',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               nullable=True)
    op.drop_column('catalogue_product', 'type_id')
    op.add_column('catalogue_category', sa.Column('name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('catalogue_category', sa.Column('description', mysql.VARCHAR(length=100), nullable=True))
    op.create_index('ix_catalogue_category_name', 'catalogue_category', ['name'], unique=True)
    op.drop_column('catalogue_category', 'category_code')
    op.drop_index(op.f('ix_catalogue_product_detail_name'), table_name='catalogue_product_detail')
    op.drop_table('catalogue_product_detail')
    op.drop_index(op.f('ix_catalogue_category_detail_name'), table_name='catalogue_category_detail')
    op.drop_index(op.f('ix_catalogue_category_detail_lang_code'), table_name='catalogue_category_detail')
    op.drop_table('catalogue_category_detail')
    op.drop_table('catalogue_product_type')
    ### end Alembic commands ###
