"""empty message

Revision ID: 9df673ad1b52
Revises: f7f55feca6d9
Create Date: 2017-01-02 17:52:33.843625

"""

# revision identifiers, used by Alembic.
revision = '9df673ad1b52'
down_revision = 'f7f55feca6d9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_association', sa.Column('upc', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'order_association', ['upc'])
    op.drop_constraint('order_association_ibfk_2', 'order_association', type_='foreignkey')
    op.drop_column('order_association', 'product_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_association', sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('order_association_ibfk_2', 'order_association', 'catalogue_product', ['product_id'], ['id'])
    op.drop_constraint(None, 'order_association', type_='unique')
    op.drop_column('order_association', 'upc')
    ### end Alembic commands ###
