"""empty message

Revision ID: a0917f0cc187
Revises: e364e92183ab
Create Date: 2017-01-02 15:10:01.246308

"""

# revision identifiers, used by Alembic.
revision = 'a0917f0cc187'
down_revision = 'e364e92183ab'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('order_id', table_name='order')
    op.drop_column('order', 'order_id')
    op.add_column('payment', sa.Column('payment_unique_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'payment', ['payment_unique_id'])
    op.create_foreign_key(None, 'payment', 'order', ['order_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_constraint(None, 'payment', type_='unique')
    op.drop_column('payment', 'payment_unique_id')
    op.add_column('order', sa.Column('order_id', mysql.VARCHAR(length=100), nullable=True))
    op.create_index('order_id', 'order', ['order_id'], unique=True)
    ### end Alembic commands ###
