"""empty message

Revision ID: a48e477afe75
Revises: b1799fbf921b
Create Date: 2017-01-23 14:26:55.992697

"""

# revision identifiers, used by Alembic.
revision = 'a48e477afe75'
down_revision = 'b1799fbf921b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_return_ibfk_1', 'product_return', type_='foreignkey')
    op.drop_constraint('product_return_ibfk_2', 'product_return', type_='foreignkey')
    op.create_foreign_key(None, 'product_return', 'catalogue_product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'product_return', 'order_association', ['order_id'], ['order_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_return', type_='foreignkey')
    op.drop_constraint(None, 'product_return', type_='foreignkey')
    op.create_foreign_key('product_return_ibfk_2', 'product_return', 'order_association', ['product_id'], ['order_id'])
    op.create_foreign_key('product_return_ibfk_1', 'product_return', 'order_association', ['order_id'], ['product_id'])
    ### end Alembic commands ###
