"""empty message

Revision ID: a935d4808719
Revises: 5445fdb31bfd
Create Date: 2016-12-13 15:07:16.473214

"""

# revision identifiers, used by Alembic.
revision = 'a935d4808719'
down_revision = '5445fdb31bfd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.DECIMAL(), nullable=True),
    sa.Column('shipping_fee', sa.DECIMAL(), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(), nullable=True),
    sa.Column('shipping_method', sa.String(length=65), nullable=True),
    sa.Column('order_state', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=65), nullable=True),
    sa.Column('billing_province', sa.String(length=80), nullable=True),
    sa.Column('billing_addr1', sa.String(length=80), nullable=True),
    sa.Column('billing_addr2', sa.String(length=80), nullable=True),
    sa.Column('billing_addr3', sa.String(length=80), nullable=True),
    sa.Column('shipping_province', sa.String(length=80), nullable=True),
    sa.Column('shipping_addr1', sa.String(length=80), nullable=True),
    sa.Column('shipping_addr2', sa.String(length=80), nullable=True),
    sa.Column('shipping_addr3', sa.String(length=80), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_table('order_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalogue_product.id'], ),
    sa.PrimaryKeyConstraint('id', 'product_id', 'order_id')
    )
    op.drop_table('payment_method')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_method',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('modified_at', mysql.DATETIME(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('order_association')
    op.drop_table('order')
    ### end Alembic commands ###
