"""empty message

Revision ID: aadd4febd560
Revises: f3298d01604a
Create Date: 2017-02-05 20:56:48.955891

"""

# revision identifiers, used by Alembic.
revision = 'aadd4febd560'
down_revision = 'f3298d01604a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wireless_recharge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('status_description', sa.String(length=255), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('activated_wireless', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activated_wireless'], ['wireless_sim_activate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wireless_recharge')
    ### end Alembic commands ###
