"""empty message

Revision ID: b1799fbf921b
Revises: 575c0f133a28
Create Date: 2017-01-23 11:58:05.081187

"""

# revision identifiers, used by Alembic.
revision = 'b1799fbf921b'
down_revision = '575c0f133a28'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_return', sa.Column('contact_number', sa.String(length=15), nullable=True))
    op.add_column('product_return', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('product_return', sa.Column('message', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_return', 'message')
    op.drop_column('product_return', 'email')
    op.drop_column('product_return', 'contact_number')
    ### end Alembic commands ###
