"""empty message

Revision ID: b72f03296cc5
Revises: None
Create Date: 2016-11-01 10:49:12.741566

"""

# revision identifiers, used by Alembic.
revision = 'b72f03296cc5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_country',
    sa.Column('iso_3166_1_a2', sa.CHAR(length=2), nullable=False),
    sa.Column('iso_3166_1_a3', sa.CHAR(length=3), nullable=True),
    sa.Column('iso_3166_1_numeric', sa.CHAR(length=3), nullable=True),
    sa.Column('printable_name', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('display_order', sa.SmallInteger(), nullable=True),
    sa.Column('is_shipping_country', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('iso_3166_1_a2')
    )
    op.create_index(op.f('ix_address_country_display_order'), 'address_country', ['display_order'], unique=False)
    op.create_index(op.f('ix_address_country_is_shipping_country'), 'address_country', ['is_shipping_country'], unique=False)
    op.create_table('auth_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.Column('business_number', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('housing_mainlocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=55), nullable=True),
    sa.Column('realname', sa.String(length=55), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('addressLat', sa.String(length=63), nullable=True),
    sa.Column('addressLong', sa.String(length=63), nullable=True),
    sa.Column('northeastLat', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('northeastLng', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('southwestLat', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('southwestLng', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('zoom', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=63), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('housing_private_facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('housing_public_facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('housing_searchlocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=55), nullable=True),
    sa.Column('korean_name', sa.String(length=55), nullable=True),
    sa.Column('chinese_name', sa.String(length=55), nullable=True),
    sa.Column('addressLat', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('addressLong', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('northeastLat', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('northeastLng', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('southwestLat', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('southwestLng', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('housing_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=63), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('address_country_subdivision',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('iso_3166_country', sa.CHAR(length=2), nullable=True),
    sa.Column('parent_code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['iso_3166_country'], ['address_country.iso_3166_1_a2'], ),
    sa.ForeignKeyConstraint(['parent_code'], ['address_country_subdivision.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('auth_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('current_login_ip', sa.String(length=45), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.CHAR(length=2), nullable=True),
    sa.Column('country_subdivision_code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['address_country.iso_3166_1_a2'], ),
    sa.ForeignKeyConstraint(['country_subdivision_code'], ['address_country_subdivision.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('auth_partners_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['auth_partners.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'partner_id')
    )
    op.create_table('auth_roles_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['auth_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('housing_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('housing_type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('address1', sa.String(length=200), nullable=True),
    sa.Column('address2', sa.String(length=200), nullable=True),
    sa.Column('thumbnail_image', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('min_rental_period', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['housing_type_id'], ['housing_type.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['auth_partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('housing_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('housing_service_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('vacancy', sa.Integer(), nullable=True),
    sa.Column('deposit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['housing_service_id'], ['housing_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('housing_service_public_facilities',
    sa.Column('housing_service_id', sa.Integer(), nullable=False),
    sa.Column('housing_public_facilities_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['housing_public_facilities_id'], ['housing_public_facilities.id'], ),
    sa.ForeignKeyConstraint(['housing_service_id'], ['housing_services.id'], ),
    sa.PrimaryKeyConstraint('housing_service_id', 'housing_public_facilities_id')
    )
    op.create_table('housing_booking_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('housing_room_id', sa.Integer(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('bookeddate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['housing_room_id'], ['housing_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('housing_rooms_private_facilities',
    sa.Column('housing_rooms_id', sa.Integer(), nullable=False),
    sa.Column('housing_private_facilities_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['housing_private_facilities_id'], ['housing_private_facilities.id'], ),
    sa.ForeignKeyConstraint(['housing_rooms_id'], ['housing_rooms.id'], ),
    sa.PrimaryKeyConstraint('housing_rooms_id', 'housing_private_facilities_id')
    )
    op.create_table('housing_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('housing_booking_status_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('price', sa.String(length=63), nullable=True),
    sa.Column('paid_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['housing_booking_status_id'], ['housing_booking_status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('housing_payment')
    op.drop_table('housing_rooms_private_facilities')
    op.drop_table('housing_booking_status')
    op.drop_table('housing_service_public_facilities')
    op.drop_table('housing_rooms')
    op.drop_table('housing_services')
    op.drop_table('auth_roles_users')
    op.drop_table('auth_partners_users')
    op.drop_table('auth_users')
    op.drop_table('address_country_subdivision')
    op.drop_table('housing_type')
    op.drop_table('housing_searchlocations')
    op.drop_table('housing_public_facilities')
    op.drop_table('housing_private_facilities')
    op.drop_table('housing_mainlocations')
    op.drop_table('auth_roles')
    op.drop_table('auth_partners')
    op.drop_index(op.f('ix_address_country_is_shipping_country'), table_name='address_country')
    op.drop_index(op.f('ix_address_country_display_order'), table_name='address_country')
    op.drop_table('address_country')
    ### end Alembic commands ###
