"""empty message

Revision ID: be4c00f900cf
Revises: cfe731abd628
Create Date: 2017-01-23 14:46:24.563887

"""

# revision identifiers, used by Alembic.
revision = 'be4c00f900cf'
down_revision = 'cfe731abd628'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_return', sa.Column('test', sa.String(length=255), nullable=True))
    op.alter_column('product_return', 'order_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('product_return', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint('product_return_ibfk_2', 'product_return', type_='foreignkey')
    op.create_foreign_key(None, 'product_return', 'order', ['order_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_return', type_='foreignkey')
    op.create_foreign_key('product_return_ibfk_2', 'product_return', 'order_association', ['order_id'], ['order_id'])
    op.alter_column('product_return', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('product_return', 'order_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_column('product_return', 'test')
    ### end Alembic commands ###
