"""empty message

Revision ID: c2583e59af10
Revises: 1bad5c16033e
Create Date: 2016-11-17 13:30:51.767197

"""

# revision identifiers, used by Alembic.
revision = 'c2583e59af10'
down_revision = '1bad5c16033e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('catalogue_category', 'category_code',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)
    op.create_foreign_key(None, 'catalogue_product_image', 'catalogue_product', ['product_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catalogue_product_image', type_='foreignkey')
    op.alter_column('catalogue_category', 'category_code',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
    ### end Alembic commands ###
