"""empty message

Revision ID: c7497fa98f88
Revises: 7a8eb51d4613
Create Date: 2017-01-04 14:36:35.553911

"""

# revision identifiers, used by Alembic.
revision = 'c7497fa98f88'
down_revision = '7a8eb51d4613'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_association', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('order_association', sa.Column('modified_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_association', 'modified_at')
    op.drop_column('order_association', 'created_at')
    ### end Alembic commands ###
