"""empty message

Revision ID: cfe731abd628
Revises: b6ff3e556233
Create Date: 2017-01-23 14:44:34.978700

"""

# revision identifiers, used by Alembic.
revision = 'cfe731abd628'
down_revision = 'b6ff3e556233'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_return', sa.Column('exchangeORrefund', sa.String(length=100), nullable=False))
    op.alter_column('product_return', 'order_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('product_return', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_column('product_return', 'exchange_refund')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_return', sa.Column('exchange_refund', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.alter_column('product_return', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('product_return', 'order_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_column('product_return', 'exchangeORrefund')
    ### end Alembic commands ###
