"""empty message

Revision ID: da9e8912904a
Revises: 70b530806c8e
Create Date: 2016-11-16 15:52:36.498457

"""

# revision identifiers, used by Alembic.
revision = 'da9e8912904a'
down_revision = '70b530806c8e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_catalogue_category_category_code', table_name='catalogue_category')
    op.create_unique_constraint(None, 'catalogue_category', ['category_code'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catalogue_category', type_='unique')
    op.create_index('ix_catalogue_category_category_code', 'catalogue_category', ['category_code'], unique=False)
    ### end Alembic commands ###
