"""empty message

Revision ID: e09f73da81e3
Revises: 4cba2931621e
Create Date: 2016-11-09 15:27:43.906542

"""

# revision identifiers, used by Alembic.
revision = 'e09f73da81e3'
down_revision = '4cba2931621e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housing_reservation', sa.Column('nationality', sa.String(length=55), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('housing_reservation', 'nationality')
    ### end Alembic commands ###
