"""empty message

Revision ID: e364e92183ab
Revises: 1ace91739e83
Create Date: 2017-01-02 14:39:49.347104

"""

# revision identifiers, used by Alembic.
revision = 'e364e92183ab'
down_revision = '1ace91739e83'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('shipping', sa.DECIMAL(), nullable=True))
    op.drop_column('order', 'shipping_fee')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('shipping_fee', mysql.DECIMAL(precision=10, scale=0), nullable=True))
    op.drop_column('order', 'shipping')
    ### end Alembic commands ###
