"""empty message

Revision ID: edc699045fb2
Revises: 24e7fd93ed58
Create Date: 2016-11-11 16:38:57.032831

"""

# revision identifiers, used by Alembic.
revision = 'edc699045fb2'
down_revision = '24e7fd93ed58'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wireless_sim_order', sa.Column('rcv_date', sa.Date(), nullable=True))
    op.add_column('wireless_sim_order', sa.Column('rcv_extran_address', sa.String(length=255), nullable=True))
    op.add_column('wireless_sim_order', sa.Column('user_email', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wireless_sim_order', 'user_email')
    op.drop_column('wireless_sim_order', 'rcv_extran_address')
    op.drop_column('wireless_sim_order', 'rcv_date')
    ### end Alembic commands ###
