"""empty message

Revision ID: f06018ed0da9
Revises: 3ccf989232b8
Create Date: 2017-01-02 00:25:53.318407

"""

# revision identifiers, used by Alembic.
revision = 'f06018ed0da9'
down_revision = '3ccf989232b8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_id', sa.String(length=100), nullable=True))
    op.drop_index('order_number', table_name='order')
    op.create_unique_constraint(None, 'order', ['order_id'])
    op.drop_column('order', 'order_number')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order', type_='unique')
    op.create_index('order_number', 'order', ['order_number'], unique=True)
    op.drop_column('order', 'order_id')
    ### end Alembic commands ###
