"""empty message

Revision ID: f193cd533d9a
Revises: 2c8f3286f425
Create Date: 2017-01-25 10:17:18.018384

"""

# revision identifiers, used by Alembic.
revision = 'f193cd533d9a'
down_revision = '2c8f3286f425'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wireless_sim_order', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wireless_sim_order', 'payment', ['payment_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wireless_sim_order', type_='foreignkey')
    op.drop_column('wireless_sim_order', 'payment_id')
    ### end Alembic commands ###
