"""empty message

Revision ID: f3298d01604a
Revises: 9d1c3c99b122
Create Date: 2017-02-05 17:27:49.072553

"""

# revision identifiers, used by Alembic.
revision = 'f3298d01604a'
down_revision = '9d1c3c99b122'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wireless_sim_order', sa.Column('is_actviated', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wireless_sim_order', 'is_actviated')
    ### end Alembic commands ###
