"""empty message

Revision ID: f539fed3e8c1
Revises: a935d4808719
Create Date: 2016-12-13 15:10:24.418552

"""

# revision identifiers, used by Alembic.
revision = 'f539fed3e8c1'
down_revision = 'a935d4808719'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('billing_iso_3166_country', sa.String(length=2), nullable=True))
    op.add_column('order', sa.Column('shipping_iso_3166_country', sa.String(length=2), nullable=True))
    op.create_foreign_key(None, 'order', 'address_country', ['billing_iso_3166_country'], ['iso_3166_1_a2'])
    op.create_foreign_key(None, 'order', 'address_country', ['shipping_iso_3166_country'], ['iso_3166_1_a2'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'shipping_iso_3166_country')
    op.drop_column('order', 'billing_iso_3166_country')
    ### end Alembic commands ###
