"""empty message

Revision ID: f7f55feca6d9
Revises: 7acadbf11ce0
Create Date: 2017-01-02 17:25:47.377390

"""

# revision identifiers, used by Alembic.
revision = 'f7f55feca6d9'
down_revision = '7acadbf11ce0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('paid_in_total', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('payment', sa.Column('total_refunded', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.drop_column('payment', 'total_amount_paid')
    op.drop_column('payment', 'total_amount_refunded')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('total_amount_refunded', mysql.DECIMAL(precision=10, scale=0), nullable=True))
    op.add_column('payment', sa.Column('total_amount_paid', mysql.DECIMAL(precision=10, scale=0), nullable=True))
    op.drop_column('payment', 'total_refunded')
    op.drop_column('payment', 'paid_in_total')
    ### end Alembic commands ###
