"""empty message

Revision ID: f97dd75954b0
Revises: 1f351e24ab16
Create Date: 2016-11-02 18:09:32.572836

"""

# revision identifiers, used by Alembic.
revision = 'f97dd75954b0'
down_revision = '1f351e24ab16'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogue_category', sa.Column('description', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalogue_category', 'description')
    ### end Alembic commands ###
