"""empty message

Revision ID: fc21f4e4392c
Revises: c55d80b6b635
Create Date: 2016-11-02 00:23:21.152450

"""

# revision identifiers, used by Alembic.
revision = 'fc21f4e4392c'
down_revision = 'c55d80b6b635'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogue_category', sa.Column('child_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'catalogue_category', ['name'])
    op.create_foreign_key(None, 'catalogue_category', 'catalogue_category', ['child_id'], ['id'])
    op.drop_column('catalogue_product_image', 'is_thumbnail')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogue_product_image', sa.Column('is_thumbnail', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'catalogue_category', type_='foreignkey')
    op.drop_constraint(None, 'catalogue_category', type_='unique')
    op.drop_column('catalogue_category', 'child_id')
    ### end Alembic commands ###
