"""empty message

Revision ID: dedf87b465c8
Revises: 
Create Date: 2017-02-13 12:05:20.626815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dedf87b465c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.Column('business_number', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('catalogue_category',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_code', sa.String(length=16), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('is_display', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['catalogue_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_code')
    )
    op.create_table('catalogue_product_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('additional_price', sa.DECIMAL(precision=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalogue_product_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('requires_shipping', sa.Boolean(), nullable=True),
    sa.Column('track_stock', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawl_category',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('is_display', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['crawl_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('housing_mainlocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=55), nullable=True),
    sa.Column('realname', sa.String(length=55), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('addressLat', sa.String(length=63), nullable=True),
    sa.Column('addressLong', sa.String(length=63), nullable=True),
    sa.Column('northeastLat', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('northeastLng', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('southwestLat', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('southwestLng', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('zoom', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=63), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('housing_private_facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('housing_public_facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('housing_searchlocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=55), nullable=True),
    sa.Column('korean_name', sa.String(length=55), nullable=True),
    sa.Column('chinese_name', sa.String(length=55), nullable=True),
    sa.Column('addressLat', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('addressLong', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('northeastLat', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('northeastLng', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('southwestLat', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('southwestLng', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('housing_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=63), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table(' crawl_category_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('crawl_category_id', sa.Integer(), nullable=True),
    sa.Column('lang_code', sa.CHAR(length=5), nullable=True),
    sa.ForeignKeyConstraint(['crawl_category_id'], ['crawl_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ crawl_category_detail_lang_code'), ' crawl_category_detail', ['lang_code'], unique=False)
    op.create_index(op.f('ix_ crawl_category_detail_name'), ' crawl_category_detail', ['name'], unique=True)
    op.create_table('catalogue_category_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('category_code_id', sa.Integer(), nullable=True),
    sa.Column('lang_code', sa.CHAR(length=5), nullable=True),
    sa.ForeignKeyConstraint(['category_code_id'], ['catalogue_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogue_category_detail_lang_code'), 'catalogue_category_detail', ['lang_code'], unique=False)
    op.create_index(op.f('ix_catalogue_category_detail_name'), 'catalogue_category_detail', ['name'], unique=True)
    op.create_table('catalogue_product',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('structure', sa.CHAR(length=10), nullable=True),
    sa.Column('upc', sa.String(length=64), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['catalogue_category.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['catalogue_product.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['catalogue_product_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upc')
    )
    op.create_table('catalogue_product_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('category_code_id', sa.Integer(), nullable=True),
    sa.Column('product_attribute', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['category_code_id'], ['catalogue_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawl_product',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('structure', sa.CHAR(length=10), nullable=True),
    sa.Column('upc', sa.String(length=64), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['crawl_category.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['crawl_product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upc')
    )
    op.create_table('attribute_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('catalogue_product_attribute_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['catalogue_product_attribute_id'], ['catalogue_product_attribute.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalogue_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('contact_number', sa.String(length=15), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('current_login_ip', sa.String(length=45), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.CHAR(length=2), nullable=True),
    sa.Column('country_subdivision_code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['address_country.iso_3166_1_a2'], ),
    sa.ForeignKeyConstraint(['country_subdivision_code'], ['address_country_subdivision.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('catalogue_product_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lang_code', sa.CHAR(length=5), nullable=True),
    sa.Column('product_code_id', sa.Integer(), nullable=True),
    sa.Column('is_display', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_code_id'], ['catalogue_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogue_product_detail_lang_code'), 'catalogue_product_detail', ['lang_code'], unique=False)
    op.create_index(op.f('ix_catalogue_product_detail_name'), 'catalogue_product_detail', ['name'], unique=False)
    op.create_table('catalogue_product_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('is_thumbnail', sa.Boolean(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['catalogue_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawl_product_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lang_code', sa.CHAR(length=5), nullable=True),
    sa.Column('crawl_product_id', sa.Integer(), nullable=True),
    sa.Column('is_display', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['crawl_product_id'], ['crawl_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_product_detail_lang_code'), 'crawl_product_detail', ['lang_code'], unique=False)
    op.create_index(op.f('ix_crawl_product_detail_name'), 'crawl_product_detail', ['name'], unique=False)
    op.create_table('address_user_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('iso_3166_country', sa.CHAR(length=2), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('line1', sa.String(length=80), nullable=True),
    sa.Column('line2', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('contact_no', sa.String(length=13), nullable=True),
    sa.Column('is_main_shipping', sa.Boolean(), nullable=True),
    sa.Column('is_main', sa.Boolean(), nullable=True),
    sa.Column('is_display', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['iso_3166_country'], ['address_country.iso_3166_1_a2'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_partners_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['auth_partners.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'partner_id')
    )
    op.create_table('auth_roles_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['auth_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('catalogue_product_cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.CHAR(length=10), nullable=False),
    sa.Column('date_merged', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('housing_enquiry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=55), nullable=True),
    sa.Column('email', sa.String(length=55), nullable=True),
    sa.Column('kakao_id', sa.String(length=55), nullable=True),
    sa.Column('mobile_no', sa.String(length=55), nullable=True),
    sa.Column('enquiry', sa.Text(), nullable=True),
    sa.Column('nationality', sa.String(length=55), nullable=True),
    sa.Column('enquiry_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_housing_enquiry_user_id'), 'housing_enquiry', ['user_id'], unique=False)
    op.create_table('housing_reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=55), nullable=True),
    sa.Column('email', sa.String(length=55), nullable=True),
    sa.Column('kakao_id', sa.String(length=55), nullable=True),
    sa.Column('mobile_no', sa.String(length=55), nullable=True),
    sa.Column('checkin_date', sa.String(length=100), nullable=True),
    sa.Column('checkout_date', sa.String(length=100), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('nationality', sa.String(length=55), nullable=True),
    sa.Column('reservation_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_housing_reservation_user_id'), 'housing_reservation', ['user_id'], unique=False)
    op.create_table('housing_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('housing_type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('address1', sa.String(length=200), nullable=True),
    sa.Column('address2', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('min_rental_period', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['housing_type_id'], ['housing_type.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['auth_partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(length=20), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('shipping_fee', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('shipping_method', sa.String(length=65), nullable=True),
    sa.Column('order_state', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=65), nullable=True),
    sa.Column('billing_iso_3166_country', sa.String(length=2), nullable=True),
    sa.Column('billing_state', sa.String(length=80), nullable=True),
    sa.Column('billing_city', sa.String(length=80), nullable=True),
    sa.Column('billing_line1', sa.String(length=80), nullable=True),
    sa.Column('billing_line2', sa.String(length=80), nullable=True),
    sa.Column('shipping_iso_3166_country', sa.String(length=2), nullable=True),
    sa.Column('shipping_state', sa.String(length=80), nullable=True),
    sa.Column('shipping_city', sa.String(length=80), nullable=True),
    sa.Column('shipping_line1', sa.String(length=80), nullable=True),
    sa.Column('shipping_line2', sa.String(length=80), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['billing_iso_3166_country'], ['address_country.iso_3166_1_a2'], ),
    sa.ForeignKeyConstraint(['shipping_iso_3166_country'], ['address_country.iso_3166_1_a2'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wireless_sim_activate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('english_name', sa.String(length=50), nullable=True),
    sa.Column('id_number', sa.String(length=30), nullable=True),
    sa.Column('birthday', sa.CHAR(length=8), nullable=True),
    sa.Column('contact_no', sa.String(length=16), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('nationality_iso_3166_country', sa.CHAR(length=2), nullable=True),
    sa.Column('call_plan', sa.String(length=10), nullable=True),
    sa.Column('phone_model', sa.String(length=30), nullable=True),
    sa.Column('imei', sa.String(length=30), nullable=True),
    sa.Column('sim_number', sa.String(length=20), nullable=True),
    sa.Column('passport_img', sa.String(length=255), nullable=True),
    sa.Column('sim_type', sa.CHAR(length=2), nullable=True),
    sa.Column('active_number', sa.String(length=16), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('status_description', sa.String(length=255), nullable=True),
    sa.Column('activate_date', sa.DateTime(), nullable=True),
    sa.Column('deactivate_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nationality_iso_3166_country'], ['address_country.iso_3166_1_a2'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wireless_sim_activate_user_id'), 'wireless_sim_activate', ['user_id'], unique=False)
    op.create_table('catalogue_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['catalogue_product_cart.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalogue_product.id'], ),
    sa.PrimaryKeyConstraint('id', 'product_id', 'cart_id')
    )
    op.create_table('housing_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('housing_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('is_thumbnail', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['housing_id'], ['housing_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('housing_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('housing_service_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('vacancy', sa.Integer(), nullable=True),
    sa.Column('deposit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['housing_service_id'], ['housing_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('housing_service_public_facilities',
    sa.Column('housing_service_id', sa.Integer(), nullable=False),
    sa.Column('housing_public_facilities_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['housing_public_facilities_id'], ['housing_public_facilities.id'], ),
    sa.ForeignKeyConstraint(['housing_service_id'], ['housing_services.id'], ),
    sa.PrimaryKeyConstraint('housing_service_id', 'housing_public_facilities_id')
    )
    op.create_table('order_association',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalogue_product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'order_id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('payment_unique_id', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=20), nullable=True),
    sa.Column('paid_in_total', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_refunded', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_unique_id')
    )
    op.create_table('housing_booking_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('housing_room_id', sa.Integer(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('bookeddate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['housing_room_id'], ['housing_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('housing_rooms_private_facilities',
    sa.Column('housing_rooms_id', sa.Integer(), nullable=False),
    sa.Column('housing_private_facilities_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['housing_private_facilities_id'], ['housing_private_facilities.id'], ),
    sa.ForeignKeyConstraint(['housing_rooms_id'], ['housing_rooms.id'], ),
    sa.PrimaryKeyConstraint('housing_rooms_id', 'housing_private_facilities_id')
    )
    op.create_table('product_return',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('exchangeORrefund', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('contact_number', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order_association.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['order_association.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('is_thumbnail', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['housing_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wireless_recharge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('status_description', sa.String(length=255), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('activated_wireless_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activated_wireless_id'], ['wireless_sim_activate.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wireless_recharge_user_id'), 'wireless_recharge', ['user_id'], unique=False)
    op.create_table('wireless_sim_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('sim_type', sa.CHAR(length=2), nullable=True),
    sa.Column('phone_type', sa.String(length=30), nullable=True),
    sa.Column('sim_number', sa.String(length=20), nullable=True),
    sa.Column('shipping_address_id', sa.Integer(), nullable=True),
    sa.Column('shipping_message', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('order_state', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('is_actviated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['shipping_address_id'], ['address_user_address.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wireless_sim_order_user_id'), 'wireless_sim_order', ['user_id'], unique=False)
    op.create_table('housing_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('housing_booking_status_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('price', sa.String(length=63), nullable=True),
    sa.Column('paid_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['housing_booking_status_id'], ['housing_booking_status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('housing_payment')
    op.drop_index(op.f('ix_wireless_sim_order_user_id'), table_name='wireless_sim_order')
    op.drop_table('wireless_sim_order')
    op.drop_index(op.f('ix_wireless_recharge_user_id'), table_name='wireless_recharge')
    op.drop_table('wireless_recharge')
    op.drop_table('room_image')
    op.drop_table('product_return')
    op.drop_table('housing_rooms_private_facilities')
    op.drop_table('housing_booking_status')
    op.drop_table('payment')
    op.drop_table('order_association')
    op.drop_table('housing_service_public_facilities')
    op.drop_table('housing_rooms')
    op.drop_table('housing_image')
    op.drop_table('catalogue_association')
    op.drop_index(op.f('ix_wireless_sim_activate_user_id'), table_name='wireless_sim_activate')
    op.drop_table('wireless_sim_activate')
    op.drop_table('order')
    op.drop_table('housing_services')
    op.drop_index(op.f('ix_housing_reservation_user_id'), table_name='housing_reservation')
    op.drop_table('housing_reservation')
    op.drop_index(op.f('ix_housing_enquiry_user_id'), table_name='housing_enquiry')
    op.drop_table('housing_enquiry')
    op.drop_table('catalogue_product_cart')
    op.drop_table('auth_roles_users')
    op.drop_table('auth_partners_users')
    op.drop_table('address_user_address')
    op.drop_index(op.f('ix_crawl_product_detail_name'), table_name='crawl_product_detail')
    op.drop_index(op.f('ix_crawl_product_detail_lang_code'), table_name='crawl_product_detail')
    op.drop_table('crawl_product_detail')
    op.drop_table('catalogue_product_image')
    op.drop_index(op.f('ix_catalogue_product_detail_name'), table_name='catalogue_product_detail')
    op.drop_index(op.f('ix_catalogue_product_detail_lang_code'), table_name='catalogue_product_detail')
    op.drop_table('catalogue_product_detail')
    op.drop_table('auth_users')
    op.drop_table('attribute_association')
    op.drop_table('crawl_product')
    op.drop_table('catalogue_product_attribute')
    op.drop_table('catalogue_product')
    op.drop_index(op.f('ix_catalogue_category_detail_name'), table_name='catalogue_category_detail')
    op.drop_index(op.f('ix_catalogue_category_detail_lang_code'), table_name='catalogue_category_detail')
    op.drop_table('catalogue_category_detail')
    op.drop_index(op.f('ix_ crawl_category_detail_name'), table_name=' crawl_category_detail')
    op.drop_index(op.f('ix_ crawl_category_detail_lang_code'), table_name=' crawl_category_detail')
    op.drop_table(' crawl_category_detail')
    op.drop_table('housing_type')
    op.drop_table('housing_searchlocations')
    op.drop_table('housing_public_facilities')
    op.drop_table('housing_private_facilities')
    op.drop_table('housing_mainlocations')
    op.drop_table('crawl_category')
    op.drop_table('catalogue_product_type')
    op.drop_table('catalogue_product_option')
    op.drop_table('catalogue_category')
    op.drop_table('auth_roles')
    op.drop_table('auth_partners')
    ### end Alembic commands ###
